# # This is a basic workflow to help you get started with Actions

# name: update readme

# # Controls when the workflow will run
# on:
#   # Triggers the  workflow on push or pull request events but only for the main branch
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]
    
#   workflow_dispatch:

# jobs:
#   publish:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v2
#       with:
#         fetch-depth: 0
#     - name: Generate README.md
#       uses: probablykasper/readme-template-action@v1
#       with:
#         token: ${{ secrets.README_TEMPLATE_TOKEN }}
#         template: TEMPLATE.md
#         output: README.md
#     - name: Update README.md
#       run: |
#         if [[ "$(git status --porcelain)" != "" ]]; then
#           git config user.name "GitHub Action"
#           git config user.email "action@github.com"
#           git add .
#           git commit -m "Auto-update README.md"
#           git push
#         fi
#
